name: Python package - SunTopicModel

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"] 
        # for now: excluded 3.12 for issues with distutils

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip
          pip install -r ci_requirements.txt
          pip install .
      - name: Test with pytest
        run: pytest